=== vyra-entity/vyra_base_python/res/schema_callables.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://example.com/function.schema.json",
    "title": "Function List Schema",
    "description": "Schema f√ºr eine Liste von Funktionsdefinitionen.",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "function_name": { 
                "type": "string" 
            },
            "displayname": {
                "type": "string",
                "additionalProperties": false
            },
            "params": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                    "datatype": { 
                        "type": "string" 
                    },
                    "displayname": {
                        "type": "string"
                    },
                    "description": { 
                        "type": "string" 
                    },
                    "optional": { 
                        "type": "boolean",
                        "default": false
                    }
                    },
                    "required": ["datatype", "displayname", "description", "optional"],
                    "additionalProperties": false
                }
            },
            "return": {
                "type": "object",
                "properties": {
                    "datatype": { 
                        "type": "string" 
                    },
                    "displayname": {
                        "type": "string"
                    },
                    "description": { 
                        "type": "string" 
                    },
                    "additionalProperties": false
                },
                "required": ["datatype", "displayname", "description"],
                "additionalProperties": false
            },
            "description": { "type": "string" },
            "display_style": {
                "type": "object",
                "properties": {
                    "visible": { 
                        "type": "boolean" 
                    },
                    "published": { 
                        "type": "boolean" 
                    }
                },
                "additionalProperties": false
            },
            "additionalProperties": false
        }
    },
    "required": [
        "function_name",
        "displayname",
        "params",
        "return",
        "description",
        "visible",
        "published"
    ],
    "additionalProperties": false
}

=== vyra-entity/vyra_base_python/res/callables_core_settings.json
[
    {
        "function_name": "kill",
        "displayname": "Kill",
        "params": [
            {
                "datatype": "str",
                "displayname": "User",
                "description": "",
                "optional": false
            },
            {
                "datatype": "str",
                "displayname": "Password",
                "description": "",
                "optional": false
            },
            {
                "datatype": "str",
                "displayname": "Id",
                "description": "",
                "optional": false
            }
        ],
        "return": {
            "datatype": "str",
            "displayname": "Returnvalue",
            "description": ""
        },
        "description": "Kill the module",
        "display_style": {
            "visible": true,
            "published": false
        }
    },
    {
        "function_name": "debug",
        "displayname": "Debug",
        "params": [
            {
                "datatype": "str",
                "displayname": "1",
                "description": "Please contact developer",
                "optional": false
            },
            {
                "datatype": "str",
                "displayname": "2",
                "description": "Please contact developer",
                "optional": false
            },
            {
                "datatype": "str",
                "displayname": "3",
                "description": "Please contact developer",
                "optional": false
            }
        ],
        "return": {
            "datatype": "str",
            "displayname": "Returnvalue",
            "description": ""
        },
        "description": "Exclusively to use by the development team!!",
        "display_style": {
            "visible": true,
            "published": false
        }
    },
    {
        "function_name": "download_logging_file",
        "displayname": "Download Log",
        "params": [],
        "return": {
            "datatype": "str",
            "displayname": "Returnvalue",
            "description": ""
        },
        "description": "Download Logging file from module",
        "display_style": {
            "visible": true,
            "published": false
        }
    },
    {
        "function_name": "download_license_file",
        "displayname": "Download Licenses",
        "params": [],
        "return": {
            "datatype": "str",
            "displayname": "Returnvalue",
            "description": ""
        },
        "description": "Download License file from module",
        "display_style": {
            "visible": true,
            "published": false
        }
    },
    {
        "function_name": "upload_update",
        "displayname": "Upload Update",
        "params": [
            {
                "datatype": "str",
                "displayname": "Username",
                "description": "",
                "optional": true
            },
            {
                "datatype": "str",
                "displayname": "Password",
                "description": "",
                "optional": true
            },
            {
                "datatype": "bytestr",
                "displayname": "file",
                "description": "Updatefile. Must contain a .zip-file",
                "optional": false
            }
        ],
        "return": {
            "datatype": "str",
            "displayname": "Returnvalue",
            "description": ""
        },
        "description": "Uploading update file to this module",
        "display_style": {
            "visible": true,
            "published": false
        }
    },
    {
        "function_name": "get_all_installed_versions",
        "displayname": "Get all installed versions",
        "params": [],
        "return": {
            "datatype": "str",
            "displayname": "Returnvalue",
            "description": "List of all installed versions"
        },
        "description": "Read and return all installed versions of this module",
        "display_style": {
            "visible": true,
            "published": false
        }
    },
    {
        "function_name": "change_running_module_version",
        "displayname": "Change running versions",
        "params": [
            {
                "datatype": "str",
                "displayname": "Version",
                "description": "The module will be switched to this version if available",
                "optional": false
            }
        ],
        "return": {
            "datatype": "str",
            "displayname": "Returnvalue",
            "description": "[True|False, <Message>]"
        },
        "description": "Change the running version of this module",
        "display_style": {
            "visible": false,
            "published": false
        }
    }
]

=== vyra-entity/vyra_base_python/res/callables_state_settings.json
[
    {
        "function_name": "activate",
        "displayname": "Activate",
        "params": [
            {
                "datatype": "str",
                "displayname": "User",
                "description": "",
                "optional": false
            },
            {
                "datatype": "str",
                "displayname": "Password",
                "description": "",
                "optional": false
            },
            {
                "datatype": "str",
                "displayname": "Id",
                "description": "",
                "optional": false
            }
        ],
        "return": {
            "datatype": "str",
            "displayname": "Returnvalue",
            "description": ""
        },
        "description": "Activate the module. This will unlock functions due to the access-level",
        "display_style": {
            "visible": true,
            "published": false
        }
    },
    {
        "function_name": "deactivate",
        "displayname": "Deactivate",
        "params": [
            {
                "datatype": "str",
                "displayname": "User",
                "description": "",
                "optional": false
            },
            {
                "datatype": "str",
                "displayname": "Password",
                "description": "",
                "optional": false
            },
            {
                "datatype": "str",
                "displayname": "Id",
                "description": "",
                "optional": false
            }
        ],
        "return": {
            "datatype": "str",
            "displayname": "Returnvalue",
            "description": ""
        },
        "description": "Deactivate the module. This will lock most functions for access",
        "display_style": {
            "visible": true,
            "published": false
        }
    },
    {
        "function_name": "reset",
        "displayname": "Reset",
        "params": [],
        "return": {
            "datatype": "str",
            "displayname": "Returnvalue",
            "description": ""
        },
        "description": "Resetting a module if it is in Error-State",
        "display_style": {
            "visible": true,
            "published": false
        }
    },
    {
        "function_name": "stop",
        "displayname": "Stop",
        "params": [],
        "return": {
            "datatype": "str",
            "displayname": "Returnvalue",
            "description": ""
        },
        "description": "Stopping an running Module",
        "display_style": {
            "visible": true,
            "published": false
        }
    },
    {
        "function_name": "pause",
        "displayname": "Pause",
        "params": [],
        "return": {
            "datatype": "str",
            "displayname": "Returnvalue",
            "description": ""
        },
        "description": "Pausing an running Module",
        "display_style": {
            "visible": true,
            "published": false
        }
    },
    {
        "function_name": "restart",
        "displayname": "Restart",
        "params": [],
        "return": {
            "datatype": "str",
            "displayname": "Returnvalue",
            "description": ""
        },
        "description": "Used to restart the module if this module is in Pause-State",
        "display_style": {
            "visible": true,
            "published": false
        }
    },
    {
        "function_name": "configure",
        "displayname": "Configure",
        "params": [],
        "return": {
            "datatype": "str",
            "displayname": "Returnvalue",
            "description": ""
        },
        "description": "Used to restart the module if this module is in Pause-State",
        "display_style": {
            "visible": true,
            "published": false
        }
    }
]
